DiaryApp/Models/DiaryEntryModel.cs
using System.ComponentModel.DataAnnotations;

namespace DiaryApp.Models
{
    public class DiaryEntryModel
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "You need to give the entry a title.")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Your title must be between 3 and 50 characters!")]
        public required string Title { get; set; }

        [Required(ErrorMessage = "You need to write some content for the entry.")]
        [StringLength(50, MinimumLength = 5, ErrorMessage = "Your title must be between 5 and 50 characters!")]
        public required string Content { get; set; }

        [Required(ErrorMessage = "You need to pick a date for your entry.")]
        public DateTime Date { get; set; } = DateTime.Now;
    }
}

DiaryApp/Models/ErrorViewModel.cs
namespace DiaryApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DiaryApp/Controllers/DiaryEntriesController.cs
using DiaryApp.Data;
using DiaryApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace DiaryApp.Controllers
{
    public class DiaryEntriesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DiaryEntriesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<DiaryEntryModel> diaryEntries = _db.DiaryEntries.ToList();

            return View(diaryEntries);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(DiaryEntryModel diaryEntry)
        {
            ValidateInput(diaryEntry);

            if (ModelState.IsValid)
            {
                _db.DiaryEntries.Add(diaryEntry);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(diaryEntry);
        }

        public IActionResult Edit(int? id)
        {
            DiaryEntryModel? diaryEntry = _db.DiaryEntries.Find(id);

            if (diaryEntry == null)
            {
                return NotFound();
            }

            return View(diaryEntry);
        }

        [HttpPost]
        public IActionResult Edit(DiaryEntryModel diaryEntry)
        {
            ValidateInput(diaryEntry);

            if (ModelState.IsValid)
            {
                _db.DiaryEntries.Update(diaryEntry);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(diaryEntry);
        }

        public IActionResult Delete(int id)
        {
            DiaryEntryModel? diaryEntry = _db.DiaryEntries.Find(id);

            if (diaryEntry == null)
            {
                return NotFound();
            }

            _db.DiaryEntries.Remove(diaryEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public void ValidateInput(DiaryEntryModel diaryEntry)
        {
            if (diaryEntry.Title == null || diaryEntry.Content == null || diaryEntry.Date == DateTime.MinValue)
            {
                ModelState.AddModelError("Title", "You need to give the entry a title.");
                ModelState.AddModelError("Content", "You need to write some content for the entry.");
                ModelState.AddModelError("Date", "You need to pick a date for your entry.");
            }
            else if (diaryEntry.Title.Length < 3 && diaryEntry.Content.Length < 5)
            {
                ModelState.AddModelError("Title", "Your title must be between 3 and 50 characters!");
                ModelState.AddModelError("Content", "Your content must be between 5 and 50 characters!");
            }
        }
    }
}

DiaryApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using DiaryApp.Models;

namespace DiaryApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult About()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DiaryApp/Views/DiaryEntries/Create.cshtml
@{
    ViewData["Title"] = "Create New Entry";
}

@model DiaryEntryModel

<h1 class="text-success mb-3">@ViewData["Title"]</h1>

<form asp-action="" method="post">
    <fieldset>
        <div>
            <label asp-for="Title" for="diaryEntryTitle" class="form-label mt-4">Title</label>
            <input asp-for="Title" class="form-control" id="diaryEntryTitle" placeholder="Pick something cool!">
        </div>

        <div>
            <label asp-for="Content" for="diaryEntryContent" class="form-label mt-4">Content</label>
            <textarea asp-for="Title" class="form-control" id="diaryEntryContent" rows="5" placeholder="How was your day?"></textarea>
        </div>

        <div>
            <label asp-for="Date" for="diaryEntryDate" class="form-label mt-4">Date</label>
            <input asp-for="Title" type="date" class="form-control" id="diaryEntryDate" placeholder="When did all of this happen?">
        </div>

        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-success mt-4">Submit</button>
            <a class="btn btn-danger mt-4" asp-area="" asp-controller="DiaryEntries" asp-action="Index">Cancel</a>
        </div>

    </fieldset>
</form>

DiaryApp/Views/DiaryEntries/Edit.cshtml
@{
    ViewData["Title"] = "Edit Current Entry";
}

@model DiaryEntryModel

<h1 class="text-success mb-3">@ViewData["Title"]</h1>

<form asp-action="Edit" method="post">
    <fieldset>
        <div>
            <label asp-for="Title" for="diaryEntryTitle" class="form-label mt-4">Title</label>
            <input asp-for="Title" class="form-control mb-2" id="diaryEntryTitle" placeholder="Pick something cool!">
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="Content" for="diaryEntryContent" class="form-label mt-4">Content</label>
            <textarea asp-for="Content" class="form-control mb-2" id="diaryEntryContent" rows="3" placeholder="How was your day?"></textarea>
            <span asp-validation-for="Content" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="Date" for="diaryEntryDate" class="form-label mt-4">Date</label>
            <input asp-for="Date" type="date" class="form-control mb-2" id="diaryEntryDate" placeholder="When did all of this happen?">
            <span asp-validation-for="Date" class="text-danger"></span>
        </div>

        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-success mt-4">Edit</button>
            <a class="btn btn-danger mt-4" asp-area="" asp-controller="DiaryEntries" asp-action="Index">Cancel</a>
        </div>
    </fieldset>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

DiaryApp/Views/DiaryEntries/Index.cshtml
@{
    ViewData["Title"] = "Diary Entries";
}

@model List<DiaryEntryModel>

<h1 class="text-success mb-3">@ViewData["Title"]</h1>

<div class="container">
    <div class="row">
        <div class="col-md-12 text-end">
            <a class="btn btn-outline-success" asp-area="" asp-controller="DiaryEntries" asp-action="Create">Add Entry</a>
        </div>
    </div>

</div>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th class="text-success">Title</th>
                <th class="text-success">Content</th>
                <th class="text-success">Date</th>
                <th class="text-success">Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var entry in Model)
            {
                <tr>
                    <td class="text-body">@entry.Title</td>
                    <td class="text-body">@entry.Content</td>
                    <td class="text-body">@entry.Date.ToShortDateString()</td>
                    <td>
                        <a class="btn btn-warning" asp-area="" asp-controller="DiaryEntries" asp-action="Edit" asp-route-id="@entry.Id">Edit</a>
                        <a class="btn btn-danger" asp-area="" asp-controller="DiaryEntries" asp-action="Delete" asp-route-id="@entry.Id">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

DiaryApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h1 class="text-success mb-3">@ViewData["Title"]</h1>

<p class="nav-link">A diary application with fully functioning CRUD Operations using ASP.NET Core 8 MVC, Razor Pages, Entity Framework and Microsoft SQL.</p>

DiaryApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4 mb-3 text-success">Welcome!</h1>

    <figure class="text-center mb-3">
        <blockquote class="blockquote">
            <p class="mb-0">We all die. The goal isn't to live forever, the goal is to create something that will.</p>

        </blockquote>
        <figcaption class="blockquote-footer">
            Chuck Palahniuk in <cite title="Source Title">Diary</cite>
        </figcaption>
    </figure>

    <div class="d-grid gap-2">
        <button class="btn btn-lg btn-outline-success" type="button">
                <a class="nav-link text-body" asp-area="" asp-controller="DiaryEntries" asp-action="Index">Click here to see your diary!</a>
        </button>
    </div>


</div>

DiaryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Diary</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DiaryApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-dark mb-3 border border-2 border-success rounded">
            <div class="container-fluid">
                <a class="navbar-brand link-success" asp-area="" asp-controller="Home" asp-action="Index"><strong>DIARY</strong></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link link-success" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-success" asp-area="" asp-controller="DiaryEntries" asp-action="Index">Diary Entries</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-success" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link link-success" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2024 - Diary by <a class="text-success" href="https://www.linkedin.com/in/furkanutkuemre/">Furkan Utku EMRE</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>